apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-autoscale
  labels:
    app: demo-app-autoscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-autoscale
  template:
    metadata:
      labels:
        app: demo-app-autoscale
    spec:
      containers:
      - name: hpa-example
        # small example image that can be stressed; public image used in k8s docs
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"