---
apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
    - name: load
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            wget -q -O- http://demo-app-autoscale.default.svc.cluster.local/;
          done
  restartPolicy: Never
