---
apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  containers:
    - name: busy
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
        runAsUser: 0
        capabilities:
          add: ["ALL"]
  restartPolicy: Never
