---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-unconfined
spec:
  containers:
    - name: busy
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        seccompProfile:
          type: Unconfined
  restartPolicy: Never
