---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-preferred-affinity
  namespace: lab-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pref
  template:
    metadata:
      labels:
        app: nginx-pref
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
