apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-required-affinity
  namespace: lab-affinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-req
  template:
    metadata:
      labels:
        app: nginx-req
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80