---
apiVersion: v1
kind: Pod
metadata:
  name: taint-demo-with-tol
  namespace: lab-affinity
  labels:
    app: taint-demo
spec:
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:1.25
      ports:
        - containerPort: 80
  restartPolicy: Always
