---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
spec:
  scaleTargetRef:
    name: redis-worker
  pollingInterval: 5 # seconds
  cooldownPeriod: 30 # seconds
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: redis
      metadata:
        address: "redis:6379"
        listName: "keda-queue"
        listLength: "5"
      authenticationRef: null
